# input directory contains raw reads in fastq format
# fastq file should gzip compressed
# for paired end reads, named as {sample_id}_1.fastq.gz and {sample_id}_2.fastq.gz
# for single end reads, named as {sample_id}.fastq.gz
input_dir: /Share2/home/lulab1/exRNA/published/exoRBase/GSE100063/fastq # this paramter is required, without a default setting
# path of sample id need to processed txt file, a sample id per line
# these sample should present in input_dir
sample_ids: test_ids.txt # required
# where to save output
output_dir: output/test_pe # required
# default parameters, required
default_config: config/default.yaml 
